#!/usr/bin/env python3
"""
Project Manager — init / validate / manage drawio diagram projects.

Usage:
    python3 project_manager.py init <project_name>
    python3 project_manager.py validate <project_path>
    python3 project_manager.py list
"""

import os
import sys
import json
from datetime import datetime

PROJECTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))), "projects")


def init_project(name: str) -> str:
    """Create a new project directory structure."""
    project_path = os.path.join(PROJECTS_DIR, name)
    
    if os.path.exists(project_path):
        print(f"⚠️  Project '{name}' already exists at {project_path}")
        return project_path
    
    # Create directories
    os.makedirs(project_path, exist_ok=True)
    os.makedirs(os.path.join(project_path, "sources"), exist_ok=True)
    os.makedirs(os.path.join(project_path, "exports"), exist_ok=True)
    
    # Create project metadata
    metadata = {
        "name": name,
        "created": datetime.now().isoformat(),
        "status": "initialized",
        "template": None,
        "diagram_type": None
    }
    
    with open(os.path.join(project_path, "project.json"), "w") as f:
        json.dump(metadata, f, indent=2)
    
    print(f"✅ Project '{name}' created at {project_path}")
    print(f"   Structure:")
    print(f"   {name}/")
    print(f"   ├── sources/          # Input materials")
    print(f"   ├── exports/          # Generated .drawio files")
    print(f"   ├── project.json      # Project metadata")
    print(f"   ├── design_spec.md    # (generated by Strategist)")
    print(f"   └── spec_lock.md      # (generated by Strategist)")
    
    return project_path


def validate_project(project_path: str) -> bool:
    """Validate project structure and files."""
    errors = []
    warnings = []
    
    if not os.path.exists(project_path):
        print(f"❌ Project path does not exist: {project_path}")
        return False
    
    # Check required files
    required = ["project.json"]
    for f in required:
        if not os.path.exists(os.path.join(project_path, f)):
            errors.append(f"Missing required file: {f}")
    
    # Check optional but expected files
    expected = ["design_spec.md", "spec_lock.md"]
    for f in expected:
        if not os.path.exists(os.path.join(project_path, f)):
            warnings.append(f"Missing expected file: {f}")
    
    # Check for .drawio outputs
    exports_dir = os.path.join(project_path, "exports")
    if os.path.exists(exports_dir):
        drawio_files = [f for f in os.listdir(exports_dir) if f.endswith(".drawio")]
        if drawio_files:
            print(f"📁 Found {len(drawio_files)} .drawio file(s) in exports/")
        else:
            warnings.append("No .drawio files in exports/ yet")
    
    # Report
    if errors:
        print(f"❌ Validation FAILED ({len(errors)} errors)")
        for e in errors:
            print(f"   ❌ {e}")
    else:
        print(f"✅ Validation PASSED")
    
    if warnings:
        for w in warnings:
            print(f"   ⚠️  {w}")
    
    return len(errors) == 0


def list_projects() -> list:
    """List all projects."""
    if not os.path.exists(PROJECTS_DIR):
        print("No projects directory found.")
        return []
    
    projects = []
    for name in sorted(os.listdir(PROJECTS_DIR)):
        path = os.path.join(PROJECTS_DIR, name)
        if os.path.isdir(path) and name != ".gitkeep":
            meta_path = os.path.join(path, "project.json")
            if os.path.exists(meta_path):
                with open(meta_path) as f:
                    meta = json.load(f)
                projects.append(meta)
                print(f"  📐 {meta['name']} — {meta.get('status', 'unknown')} ({meta.get('created', '?')})")
            else:
                print(f"  📁 {name} (no metadata)")
    
    if not projects:
        print("  (no projects found)")
    
    return projects


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: project_manager.py <command> [args]")
        print("Commands: init <name>, validate <path>, list")
        sys.exit(1)
    
    cmd = sys.argv[1]
    
    if cmd == "init":
        if len(sys.argv) < 3:
            print("Usage: project_manager.py init <project_name>")
            sys.exit(1)
        init_project(sys.argv[2])
    
    elif cmd == "validate":
        if len(sys.argv) < 3:
            print("Usage: project_manager.py validate <project_path>")
            sys.exit(1)
        success = validate_project(sys.argv[2])
        sys.exit(0 if success else 1)
    
    elif cmd == "list":
        list_projects()
    
    else:
        print(f"Unknown command: {cmd}")
        sys.exit(1)
